from django.urls import path

from .endpoints.analytics import (
    CategoryInsightsView,
    InsightGroupView,
    InsightLookupView,
    InsightReportView,
    InsightsListView,
    SellerSegmentationView,
    VendorPerformanceView,
    VendorScoreView,
    VendorTrendlineView,
)
from .endpoints.financial import BudgetForecastView, PaymentReceiptSummaryView, SellerPayoutView
from .endpoints.market import (
    MarketShareView,
    MarketTrendsView,
    NarrativeDigestView,
    PeakDemandView,
    SeasonalForecastView,
)
from .endpoints.operations import (
    ChannelHealthView,
    EventAuditView,
    LogisticsAlertsView,
    PaymentLatencyView,
    ShipmentLatencyView,
)
from .endpoints.realtime import SubscriptionAuditView
from .views import (
    ActionPlaybookView,
    AtlasEndpointView,
    BenchmarkSummaryView,
    BudgetRuleView,
    CashflowForecastView,
    ComplianceAlertsView,
    DeliveryPromiseView,
    DisputeTicketDetailView,
    DisputeTicketListView,
    DynamicPricingView,
    InventoryHealthView,
    MarketIntelligenceView,
    PriceAnomalyView,
    ReconciliationSummaryView,
    RealtimeEventView,
    RealtimeStatusView,
    RealtimeSubscriptionView,
    RefundRequestDetailView,
    RefundRequestListView,
    TaxExportView,
    VendorAnalyticsView,
    VendorFunnelView,
    VendorRiskProfileView,
)

app_name = 'atlas'

FAMILY_ENDPOINTS = [
    ('overview', 'list', ''),
    ('overview', 'summary', 'summary/'),
    ('overview', 'compare', 'compare/'),
    ('overview', 'export', 'export/'),
    ('overview', 'detail', '<slug:key>/'),
    ('signals', 'list', ''),
    ('signals', 'summary', 'summary/'),
    ('signals', 'compare', 'compare/'),
    ('signals', 'export', 'export/'),
    ('signals', 'detail', '<slug:key>/'),
    ('rituals', 'list', ''),
    ('rituals', 'summary', 'summary/'),
    ('rituals', 'compare', 'compare/'),
    ('rituals', 'export', 'export/'),
    ('rituals', 'detail', '<slug:key>/'),
    ('archetypes', 'list', ''),
    ('archetypes', 'summary', 'summary/'),
    ('archetypes', 'compare', 'compare/'),
    ('archetypes', 'export', 'export/'),
    ('archetypes', 'detail', '<slug:key>/'),
    ('trends', 'list', ''),
    ('trends', 'summary', 'summary/'),
    ('trends', 'compare', 'compare/'),
    ('trends', 'export', 'export/'),
    ('trends', 'detail', '<slug:key>/'),
    ('forecasts', 'list', ''),
    ('forecasts', 'summary', 'summary/'),
    ('forecasts', 'compare', 'compare/'),
    ('forecasts', 'export', 'export/'),
    ('forecasts', 'detail', '<slug:key>/'),
    ('benchmarks', 'list', ''),
    ('benchmarks', 'summary', 'summary/'),
    ('benchmarks', 'compare', 'compare/'),
    ('benchmarks', 'export', 'export/'),
    ('benchmarks', 'detail', '<slug:key>/'),
    ('comparisons', 'list', ''),
    ('comparisons', 'summary', 'summary/'),
    ('comparisons', 'compare', 'compare/'),
    ('comparisons', 'export', 'export/'),
    ('comparisons', 'detail', '<slug:key>/'),
    ('maps', 'list', ''),
    ('maps', 'summary', 'summary/'),
    ('maps', 'compare', 'compare/'),
    ('maps', 'export', 'export/'),
    ('maps', 'detail', '<slug:key>/'),
    ('scores', 'list', ''),
    ('scores', 'summary', 'summary/'),
    ('scores', 'compare', 'compare/'),
    ('scores', 'export', 'export/'),
    ('scores', 'detail', '<slug:key>/'),
    ('chronicles', 'list', ''),
    ('chronicles', 'summary', 'summary/'),
    ('chronicles', 'compare', 'compare/'),
    ('chronicles', 'export', 'export/'),
    ('chronicles', 'detail', '<slug:key>/'),
    ('experiments', 'list', ''),
    ('experiments', 'summary', 'summary/'),
    ('experiments', 'compare', 'compare/'),
    ('experiments', 'export', 'export/'),
    ('experiments', 'detail', '<slug:key>/'),
    ('playbooks', 'list', ''),
    ('playbooks', 'summary', 'summary/'),
    ('playbooks', 'compare', 'compare/'),
    ('playbooks', 'export', 'export/'),
    ('playbooks', 'detail', '<slug:key>/'),
]

urlpatterns = [
    path(
        f'{family_slug}/{suffix}',
        AtlasEndpointView.as_view(family=family_slug, mode=mode),
        name=f'{family_slug}-{mode}',
    )
    for family_slug, mode, suffix in FAMILY_ENDPOINTS
]

urlpatterns += [
    path('vendor-analytics/', VendorAnalyticsView.as_view(), name='vendor-analytics'),
    path('vendor-analytics/<uuid:vendor_id>/', VendorAnalyticsView.as_view(), name='vendor-analytics-detail'),
    path('vendor-funnel/', VendorFunnelView.as_view(), name='vendor-funnel'),
    path('vendor-funnel/<uuid:vendor_id>/', VendorFunnelView.as_view(), name='vendor-funnel-detail'),
    path('vendor-risk/', VendorRiskProfileView.as_view(), name='vendor-risk'),
    path('vendor-risk/<uuid:vendor_id>/', VendorRiskProfileView.as_view(), name='vendor-risk-detail'),
    path('vendor-performance/', VendorPerformanceView.as_view(), name='vendor-performance'),
    path('vendor-performance/<uuid:vendor_id>/', VendorPerformanceView.as_view(), name='vendor-performance-detail'),
    path('vendor-trendline/<uuid:vendor_id>/', VendorTrendlineView.as_view(), name='vendor-trendline-detail'),
    path('vendor-score/<uuid:vendor_id>/', VendorScoreView.as_view(), name='vendor-score-detail'),
    path('seller-segmentation/', SellerSegmentationView.as_view(), name='seller-segmentation'),
    path('category-insights/', CategoryInsightsView.as_view(), name='category-insights'),
    path('inventory-health/', InventoryHealthView.as_view(), name='inventory-health'),
    path('inventory-health/<uuid:vendor_id>/', InventoryHealthView.as_view(), name='inventory-health-detail'),
    path('reconciliation-summary/', ReconciliationSummaryView.as_view(), name='reconciliation-summary'),
    path('reconciliation-summary/<uuid:vendor_id>/', ReconciliationSummaryView.as_view(), name='reconciliation-summary-detail'),
    path('market-benchmarks/', BenchmarkSummaryView.as_view(), name='market-benchmarks'),
    path('compliance-alerts/', ComplianceAlertsView.as_view(), name='compliance-alerts'),
    path('dynamic-pricing/', DynamicPricingView.as_view(), name='dynamic-pricing'),
    path('dynamic-pricing/<uuid:vendor_id>/', DynamicPricingView.as_view(), name='dynamic-pricing-detail'),
    path('delivery-promises/', DeliveryPromiseView.as_view(), name='delivery-promises'),
    path('action-playbook/', ActionPlaybookView.as_view(), name='action-playbook'),
    path('market-share/', MarketShareView.as_view(), name='market-share'),
    path('market-trends/', MarketTrendsView.as_view(), name='market-trends'),
    path('seasonal-forecast/', SeasonalForecastView.as_view(), name='seasonal-forecast'),
    path('peak-demand/', PeakDemandView.as_view(), name='peak-demand'),
    path('narrative-digest/', NarrativeDigestView.as_view(), name='narrative-digest'),
    path('insights/', InsightsListView.as_view(), name='insights'),
    path('insights/report/', InsightReportView.as_view(), name='insight-report'),
    path('insights/groups/', InsightGroupView.as_view(), name='insight-groups'),
    path('insights/<slug:slug>/', InsightLookupView.as_view(), name='insight-lookup'),
    path('market-intelligence/', MarketIntelligenceView.as_view(), name='market-intelligence'),
    path('market-intelligence/anomalies/', PriceAnomalyView.as_view(), name='market-anomalies'),
    path('payment-latency/', PaymentLatencyView.as_view(), name='payment-latency'),
    path('shipment-latency/', ShipmentLatencyView.as_view(), name='shipment-latency'),
    path('logistics-alerts/', LogisticsAlertsView.as_view(), name='logistics-alerts'),
    path('channel-health/', ChannelHealthView.as_view(), name='channel-health'),
    path('event-audit/', EventAuditView.as_view(), name='event-audit'),
    path('subscription-audit/', SubscriptionAuditView.as_view(), name='subscription-audit'),
    path('payment-receipts/', PaymentReceiptSummaryView.as_view(), name='payment-receipts'),
    path('budget-forecast/', BudgetForecastView.as_view(), name='budget-forecast'),
    path('seller-payouts/', SellerPayoutView.as_view(), name='seller-payouts'),
    path('refunds/', RefundRequestListView.as_view(), name='refund-requests'),
    path('refunds/<uuid:refund_id>/', RefundRequestDetailView.as_view(), name='refund-request-detail'),
    path('disputes/', DisputeTicketListView.as_view(), name='disputes'),
    path('disputes/<uuid:dispute_id>/', DisputeTicketDetailView.as_view(), name='dispute-detail'),
    path('budget-rules/', BudgetRuleView.as_view(), name='budget-rules'),
    path('cashflow-forecast/', CashflowForecastView.as_view(), name='cashflow-forecast'),
    path('tax-export/', TaxExportView.as_view(), name='tax-export'),
    path('realtime-events/', RealtimeEventView.as_view(), name='realtime-events'),
    path('realtime-subscriptions/', RealtimeSubscriptionView.as_view(), name='realtime-subscriptions'),
    path('realtime-status/', RealtimeStatusView.as_view(), name='realtime-status'),
]
