"""
Django settings for core_api project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-%@#up+fmq#i9eqxiavk(r+-l)$-&y1i7d&bsn7slia2fv0vauo'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'corsheaders',
    'django_filters',
    # Third-party Storage
    'cloudinary_storage',
    'cloudinary',
    # Project apps
    'users',
    'market',
    'finance',
    'ecommerce',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

USE_SQLITE = os.environ.get('USE_SQLITE', '').lower() in ('true', '1', 'yes')
if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    from django.core.exceptions import ImproperlyConfigured

    def _require_env(name: str) -> str:
        value = os.environ.get(name)
        if value is None or str(value).strip() == '':
            raise ImproperlyConfigured(
                f'Missing required environment variable {name}. '
                'Set USE_SQLITE=true to run with SQLite for local development.'
            )
        return value

    DB_HOST = _require_env('DB_HOST')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _require_env('DB_NAME'),
            'USER': _require_env('DB_USER'),
            'PASSWORD': _require_env('DB_PASSWORD'),
            'HOST': DB_HOST,
            'PORT': _require_env('DB_PORT'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Allow business query params like ?format=pdf for export endpoints.
    'URL_FORMAT_OVERRIDE': None,
}

# drf-yasg — Swagger UI (session login disabled; use Bearer JWT in Authorize)
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': (
                'Paste ONE access token only. Format: Bearer eyJ... (single JWT, three parts). '
                'Do not paste the whole JSON from login, multiple tokens, or quotes. '
                'Copy only the string value of the "access" field from POST /api/auth/token/.'
            ),
        },
    },
    'JSON_EDITOR': True,
    'SHOW_REQUEST_HEADERS': True,
}

# JWT (Simple JWT)
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# CORS - allow frontend origin(s)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Week 3 — password reset emails link to the Next.js app (forgot / reset password pages)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')
PASSWORD_RESET_FRONTEND_PATH = os.environ.get(
    'PASSWORD_RESET_FRONTEND_PATH',
    '/reset-password',
)

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'SpendSense <noreply@spendsense.local>')
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'
    if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend',
)
# Real-time (Express + Socket.io) — optional bridge when Notification is saved
REALTIME_INTERNAL_URL = os.environ.get(
    'REALTIME_INTERNAL_URL',
    'http://127.0.0.1:3001' if DEBUG else '',
).rstrip('/')
REALTIME_INTERNAL_TOKEN = os.environ.get('REALTIME_INTERNAL_TOKEN', 'dev-only-change-me')

# Optional: Redis PUB/SUB for realtime (Django publishes; Express subscribes).
# When unset, Django falls back to HTTP POST to REALTIME_INTERNAL_URL/internal/emit.
REDIS_URL = os.environ.get('REDIS_URL', '').strip()

PAYMENT_WEBHOOK_SECRET = os.environ.get('PAYMENT_WEBHOOK_SECRET', '')
CHAPA_SECRET_KEY = os.environ.get('CHAPA_SECRET_KEY', '')
CHAPA_INIT_URL = os.environ.get('CHAPA_INIT_URL', 'https://api.chapa.co/v1/transaction/initialize')
CHAPA_RETURN_URL = os.environ.get(
    'CHAPA_RETURN_URL',
    f"{FRONTEND_URL.rstrip('/')}/shop/payment/return",
)
CHAPA_CALLBACK_URL = os.environ.get(
    'CHAPA_CALLBACK_URL',
    'http://127.0.0.1:8000/api/ecommerce/webhooks/payment/',
)
CHAPA_USE_MOCK = os.environ.get('CHAPA_USE_MOCK', 'true' if DEBUG else 'false').lower() in ('1', 'true', 'yes')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cloudinary Settings
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

# Use Cloudinary whenever credentials are present (dev + prod).
# Set USE_LOCAL_STORAGE=true in .env only to explicitly opt-out during offline work.
_cloudinary_configured = all([
    os.environ.get('CLOUDINARY_CLOUD_NAME'),
    os.environ.get('CLOUDINARY_API_KEY'),
    os.environ.get('CLOUDINARY_API_SECRET'),
])
_force_local = os.environ.get('USE_LOCAL_STORAGE', 'false').lower() in ('true', '1', 'yes')

if _cloudinary_configured and not _force_local:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
